export const COLORS = {
  WHITE: '#ffffff',
  BLACK: '#20232a',
  RED: '#ff3030',
  BACKGROUND_ASH: '#f5f5f5',
  PLACEHOLDER_ASH: '#c9c9c9',
  ICON_ASH: '#8f8f8f',
  PRIMARY_COLOR: '#A52A2A',
  PRIMARY_BLUE: '#007FFF',
  LIGHT_BLUE: '#61dafb',
  BACKGROUND_BLUE: '#99FFFF',
  BACKGROUND_GREEN:'#ABEBC6',
  BACKGROUND_PURPLE:'#AED6F1',
  LIME_GREEN: '#00FF00',
  DARK_GREEN:'#186A3B',
  THEME_COLOR:'#FFFEEC',
  FILTER_COLOR:'#0B5345',
  LABEL_BG:'#BDC3C7'
};
export const APP_NAME = 'WoodVibes';
export const AGENT_CONTACT = '0702177781';
export const CLIENT_NAME = 'admin';
export const CLIENT_SECRET = '';

export const StorageStrings={
  LOGGED:'LOGGED',
  ACCESS_TOKEN:'ACCESS_TOKEN',
  REFRESH_TOKEN:'REFRESH_TOKEN',
  FACTORYID:'FACTORYID',
  ROLE:'ROLE',
  USER_ID:'USER_ID'
}
